#line 2 "lex.yy.c"

#line 4 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 130
#define YY_END_OF_BUFFER 131
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[675] =
    {   0,
        0,    0,  131,  129,  128,  128,  129,  127,   98,  102,
      129,  113,  114,   96,   94,  104,   95,  106,  101,  124,
      105,  103,  115,  109,  116,  125,  125,  125,  110,  111,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  107,
      129,  108,  128,  120,  127,    0,  126,  127,   98,  122,
      112,  100,   97,    0,  124,  117,  119,  118,  125,  125,
      125,  125,  125,    4,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,   88,  125,

      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  121,    0,  100,    0,   97,
      123,   70,   71,   72,   73,   66,   67,   68,   69,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,    5,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,   81,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,

      125,  125,  125,  125,  125,    0,   99,  125,  125,  125,
      125,  125,   50,   84,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,   89,  125,  125,  125,  125,  125,
      125,  125,   48,   49,   52,  125,   57,   90,  125,  125,
      125,  125,  125,   51,   47,  125,  125,  125,   86,  125,
      125,  125,  125,   53,  125,  125,  125,   13,  125,  125,
      125,  125,   92,  125,  125,  125,  125,   14,  125,  125,
      125,  125,    9,   85,  125,  125,  125,  125,  125,  125,
      125,  125,   93,  125,  125,   75,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,   10,   82,  125,  125,

      125,  125,  125,   45,  125,  125,  125,  125,  125,   11,
      125,  125,  125,  125,  125,  125,  125,   91,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,   87,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,    6,  125,   54,  125,  125,   12,  125,
      125,  125,    3,  125,  125,  125,  125,  125,  125,    2,
      125,  125,  125,  125,  125,  125,  125,  125,    7,  125,
       83,  125,   46,  125,  125,  125,  125,  125,  125,  125,
       32,  125,  125,  125,  125,  125,   19,   78,  125,  125,
      125,  125,  125,  125,   31,  125,  125,  125,  125,  125,

      125,  125,   80,  125,  125,  125,    1,  125,  125,  125,
       79,  125,  125,  125,  125,  125,  125,  125,  125,  125,
       35,  125,  125,  125,  125,    8,  125,  125,  125,   65,
      125,  125,  125,  125,   63,   64,   74,  125,  125,  125,
       62,  125,  125,  125,  125,  125,   58,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,   15,  125,  125,  125,  125,  125,  125,    0,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,

      125,  125,  125,   76,  125,  125,    0,   77,  125,  125,
      125,  125,  125,   42,  125,  125,  125,  125,  125,  125,
      125,    0,   16,  125,  125,  125,   56,  125,  125,  125,
      125,  125,   55,    0,    0,   23,  125,  125,  125,  125,
      125,   37,  125,  125,  125,  125,  125,  125,    0,  125,
      125,  125,   17,  125,  125,  125,  125,    0,  125,  125,
       38,  125,  125,   43,  125,  125,  125,  125,    0,    0,
       29,  125,  125,  125,  125,  125,  125,    0,  125,    0,
        0,  125,  125,    0,  125,  125,  125,  125,  125,  125,
      125,  125,    0,  125,  125,  125,  125,    0,  125,    0,

        0,    0,   25,  125,  125,    0,  125,   39,  125,   33,
      125,   44,  125,  125,    0,   61,  125,  125,  125,    0,
        0,   26,  125,    0,    0,   27,  125,  125,    0,    0,
       22,  125,  125,   30,  125,  125,    0,    0,   28,   60,
      125,  125,   34,  125,  125,  125,  125,    0,  125,  125,
       20,   18,  125,  125,   41,    0,  125,  125,   40,  125,
        0,    0,   24,   36,  125,  125,   59,  125,    0,    0,
        0,    0,   21,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   17,   22,   17,   23,   17,   24,   25,   26,
       27,   28,    1,    1,   29,   29,   29,   30,   29,   29,
       29,   29,   29,   29,   29,   29,   31,   29,   29,   29,
       32,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       33,    1,   34,    1,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   29,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        6,    1,    1
    } ;

static const flex_int16_t yy_base[699] =
    {   0,
        0,    0,  899,  900,   62,   64,  871,   65,    0,  900,
      889,  900,  900,  900,  900,  900,  868,  900,   58,   64,
      900,  900,  868,  867,  866,    0,  860,  859,  900,  900,
       34,   53,   55,   57,   43,   62,   66,   76,   76,   61,
      850,   78,   68,  833,   35,   21,   92,  838,   87,  900,
      825,  900,  112,  900,  128,  131,  900,  135,    0,  900,
      900,  875,    0,  134,  143,  900,  900,  900,    0,  149,
      153,  847,  104,    0,  846,  865,   91,  842,  828,  827,
      844,  842,  127,  822,  835,  819,  820,  137,  829,  825,
      821,  817,  160,  820,  812,  812,  826,  829,    0,  813,

      140,  826,  826,  146,  825,  821,  804,  809,  817,  801,
      145,  145,  819,  812,  150,  137,  815,  798,  802,  806,
      146,  793,  804,  803,  793,  900,  144,  834,  177,    0,
      189,    0,    0,    0,    0,    0,    0,    0,    0,  804,
      150,  794,  796,  819,  793,  790,  802,  800,  781,  797,
      790,  782,  777,  795,    0,  793,  789,  775,  783,  787,
      166,  789,  776,  801,  803,  800,  782,  778,  768,  777,
      763,  765,  774,  757,  180,  757,  763,  774,  758,  754,
      158,  749,  747,  756,  753,  757,  759,  763,  751,  752,
      763,  758,  740,  742,  750,  755,  746,  737,  737,  749,

      750,  747,  747,  738,  738,  205,  900,  736,  733,  737,
      739,  739,    0,    0,  739,  731,  726,  731,  735,  725,
      166,  728,  736,  723,    0,  727,  719,  727,  729,  725,
      709,  727,    0,    0,    0,  707,    0,    0,  712,  721,
      706,  705,  702,    0,    0,  706,  719,  699,    0,  697,
      705,  704,  700,  696,  691,  691,  710,    0,  701,  689,
      699,  691,    0,  688,  704,  690,  698,    0,  687,  697,
      686,  691,    0,    0,  693,  685,  691,  689,  688,  688,
      678,  690,    0,  676,  683,    0,  669,  684,  666,  671,
      667,  678,  657,  676,  666,  678,    0,    0,  658,  668,

      675,  657,  654,    0,  673,  654,  668,  661,  651,  668,
      662,  648,  644,  655,  643,  655,  642,    0,  640,  650,
      644,  650,  649,  636,  636,  637,  652,  632,    0,  635,
      631,  643,  642,  628,  641,  626,  643,  633,  641,  620,
      634,  617,  616,    0,  636,    0,  632,  631,    0,  618,
      623,  630,    0,  611,  626,  612,  612,  621,  607,    0,
      613,  609,  608,  621,  615,  610,  593,  601,    0,  611,
        0,  596,  596,  612,  610,  608,  609,  608,  590,  604,
        0,  606,  580,  178,  601,  590,    0,    0,  597,  600,
      598,  594,  587,  583,  596,  586,  586,  585,  576,  577,

      577,  574,    0,  568,  572,  567,    0,  570,  584,  578,
        0,  582,  561,  562,  558,  560,  573,  556,  550,  558,
        0,  552,  571,  570,  555,    0,  557,  547,  567,    0,
      565,  179,  553,  563,    0,    0,    0,  558,  541,  552,
      560,  551,  544,  550,  544,  552,    0,  534,  549,  543,
      221,  536,  547,  531,  544,  544,  526,  541,  535,  539,
      175,  530,  526,  535,  520,  522,  523,  516,  522,  525,
      532,    0,  511,  522,  512,  504,  521,  511,  227,  508,
      513,  519,  516,  502,  512,  515,  499,  511,  503,  511,
      515,  500,  512,  229,  507,  491,  501,  504,  490,  491,

      505,  491,  495,    0,  498,  482,  231,    0,  496,  494,
      494,  483,  482,    0,  471,  490,  482,  473,  471,  471,
      471,  233,    0,  489,  474,  481,    0,  467,  430,  439,
      415,  411,    0,  235,  237,  900,  239,  422,  398,  391,
      389,    0,  363,  348,  367,  357,  352,  348,  241,  194,
      360,  209,    0,  362,  246,  360,  248,  250,  346,  363,
        0,  252,  362,    0,  347,  351,  358,  340,  254,  256,
      900,  345,  334,  258,  211,  349,  335,  263,  334,  266,
      268,  346,  343,  270,  333,  337,  325,  323,  339,  336,
      339,  338,  272,  317,  332,  320,  332,  274,  323,  276,

      278,  280,  900,  316,  325,  282,  308,    0,  316,    0,
      304,    0,  308,  309,  286,    0,  319,  300,  309,  288,
      291,  900,  312,  297,  301,  900,  308,  292,  303,  305,
      900,  290,  288,    0,  307,  292,  309,  311,  900,    0,
      284,  281,    0,  276,  282,  256,  246,  316,  231,  210,
        0,    0,  186,  174,    0,  318,  144,   91,    0,   63,
      320,  322,  900,    0,   41,   33,    0,  324,  328,  330,
      342,  348,  900,  900,  409,  415,  418,  423,  429,  435,
      440,  444,  449,  453,  458,  462,  466,  470,  475,  479,
      483,  488,  493,  498,  503,  507,  512,  516

    } ;

static const flex_int16_t yy_def[699] =
    {   0,
      674,    1,  674,  674,  674,  674,  674,  675,  676,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  677,  677,  677,  674,  674,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  674,
      674,  674,  674,  674,  675,  678,  674,  675,  676,  674,
      674,  679,  680,  674,  674,  674,  674,  674,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  674,  678,  679,  679,  680,
      674,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  677,  679,  674,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  681,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,

      677,  677,  677,  677,  677,  677,  682,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  683,  677,  677,  677,  677,  677,  677,  677,  677,
      677,  677,  677,  674,  682,  674,  677,  677,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  684,  677,
      677,  677,  677,  677,  677,  677,  677,  685,  677,  677,
      677,  677,  677,  677,  677,  677,  677,  677,  674,  684,
      674,  677,  677,  677,  677,  677,  677,  686,  677,  687,
      688,  677,  677,  689,  677,  677,  677,  677,  677,  677,
      677,  677,  690,  677,  677,  677,  677,  691,  677,  692,

      674,  688,  674,  677,  677,  693,  677,  677,  677,  677,
      677,  677,  677,  677,  694,  677,  677,  677,  677,  674,
      691,  674,  677,  674,  692,  674,  677,  677,  674,  693,
      674,  677,  677,  677,  677,  677,  674,  694,  674,  677,
      677,  677,  677,  677,  677,  677,  677,  695,  677,  677,
      677,  677,  677,  677,  677,  696,  677,  677,  677,  677,
      674,  696,  674,  677,  677,  677,  677,  677,  697,  698,
      674,  698,  674,    0,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674

    } ;

static const flex_int16_t yy_nxt[964] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   20,   20,   20,
       20,   20,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   26,   29,   30,   26,   31,   32,   33,   34,   35,
       36,   37,   26,   38,   26,   26,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   26,   48,   49,   26,   26,
       50,   51,   52,   53,   53,   53,   53,   56,   62,   57,
      114,   72,  668,   63,  115,  116,  117,   73,   64,   58,
       65,   65,   65,   65,   65,   65,   65,   74,   75,   87,
       79,   88,   84,   76,   80,  667,   85,   90,   81,   89,

      105,   82,   77,  111,   83,   78,   86,   95,   91,  666,
      106,   92,   93,   53,   53,   96,   99,   94,   97,  102,
      112,   98,  103,  100,  101,  104,  108,  118,  109,  124,
       56,  119,   57,  110,  120,   57,  125,   56,  141,   57,
      145,  121,   58,  665,  122,  127,  146,  142,   57,   58,
      131,  131,  131,  131,  131,  131,  131,   64,  127,   65,
       65,   65,   65,   65,   65,   65,  132,  133,  134,  135,
      136,  137,  138,  139,  152,  153,  158,  164,  159,  165,
      173,  166,  186,  178,  188,  192,  194,  206,  189,  195,
      174,  200,  207,  209,  175,  179,  210,  251,  201,  187,

      244,  288,  245,  664,  193,  131,  131,  131,  131,  131,
      131,  131,  229,  252,  422,  206,  463,  660,  423,  230,
      674,  289,  479,  479,  489,  659,  464,  490,  479,  479,
      522,  522,  534,  534,  522,  522,  534,  534,  534,  534,
      558,  558,  569,  569,  572,  573,  575,  578,  578,  580,
      580,  558,  558,  584,  584,  569,  569,  569,  569,  593,
      593,  594,  658,  576,  578,  578,  595,  580,  580,  601,
      601,  584,  584,  593,  593,  620,  620,  624,  624,  601,
      601,  601,  601,  629,  629,  657,  585,  637,  637,  620,
      620,  536,  620,  620,  655,  536,  654,  536,  624,  624,

      653,  571,  624,  624,  629,  629,  629,  629,  648,  648,
      637,  637,  637,  637,  571,  652,  571,  648,  648,  661,
      661,  661,  661,  661,  661,  669,  669,  651,  603,  669,
      669,  671,  671,  650,  622,  649,  626,  647,  603,  646,
      603,  645,  631,  671,  671,  644,  639,  643,  622,  671,
      671,  622,  642,  641,  640,  636,  635,  626,  634,  633,
      632,  626,  628,  631,  627,  631,  623,  619,  618,  639,
      617,  639,  616,  614,  613,  612,  611,  610,  663,  609,
      663,  608,  663,  607,  605,  604,  599,  597,  596,  592,
      673,  591,  590,  589,  588,  587,  586,  583,  582,  579,

      577,  574,  673,  568,  567,  566,  565,  564,  673,   55,
       55,   55,   55,   55,   55,   59,   59,  563,   59,   59,
       59,   69,   69,   56,   56,   56,   56,   56,   56,  128,
      128,  128,  128,  128,  128,  130,  130,  562,  130,  130,
      130,  507,  507,  561,  507,  535,  535,  535,  535,  535,
      549,  549,  560,  549,  570,  570,  570,  570,  570,  581,
      581,  559,  581,  598,  598,  557,  598,  600,  600,  556,
      600,  602,  602,  602,  602,  602,  606,  606,  555,  606,
      615,  615,  554,  615,  621,  621,  621,  621,  621,  625,
      625,  625,  625,  625,  630,  630,  630,  630,  630,  638,

      638,  638,  638,  638,  656,  656,  553,  656,  662,  662,
      662,  662,  662,  670,  670,  552,  670,  672,  672,  672,
      672,  672,  551,  550,  548,  547,  546,  545,  544,  543,
      542,  541,  540,  539,  538,  537,  533,  532,  531,  530,
      529,  528,  527,  526,  525,  524,  523,  521,  520,  519,
      518,  517,  516,  515,  514,  513,  512,  511,  510,  509,
      508,  506,  505,  504,  503,  502,  501,  500,  499,  498,
      497,  496,  495,  494,  493,  492,  491,  488,  487,  486,
      485,  484,  483,  482,  481,  480,  478,  477,  476,  475,
      474,  473,  472,  471,  470,  469,  468,  467,  466,  465,

      462,  461,  460,  459,  458,  457,  456,  455,  454,  453,
      452,  451,  450,  449,  448,  447,  446,  445,  444,  443,
      442,  441,  440,  439,  438,  437,  436,  435,  434,  433,
      432,  431,  430,  429,  428,  427,  426,  425,  424,  421,
      420,  419,  381,  418,  417,  416,  415,  414,  413,  412,
      411,  410,  409,  408,  407,  406,  405,  404,  403,  402,
      401,  400,  399,  398,  397,  396,  395,  394,  393,  392,
      391,  390,  389,  388,  387,  386,  385,  384,  383,  382,
      381,  380,  379,  378,  377,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  367,  366,  365,  364,  363,  362,

      361,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      311,  310,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  294,  293,  292,
      291,  290,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  277,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,

      259,  258,  257,  256,  255,  254,  253,  250,  249,  248,
      247,  246,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  208,  129,  205,  204,  203,  202,  199,
      198,  197,  196,  191,  190,  185,  184,  183,  182,  181,
      180,  177,  176,  172,  171,  170,  169,  168,  167,  163,
      162,  161,  160,  157,  156,  155,  154,  151,  150,  149,
      148,  147,  144,  143,  140,  129,  126,  123,  113,  107,
       71,   70,   68,   67,   66,   61,   60,   54,  674,    3,

      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674
    } ;

static const flex_int16_t yy_chk[964] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    6,    6,    8,   19,    8,
       45,   31,  666,   19,   45,   46,   46,   31,   20,    8,
       20,   20,   20,   20,   20,   20,   20,   31,   32,   35,
       33,   35,   34,   32,   33,  665,   34,   36,   33,   35,

       40,   33,   32,   43,   33,   32,   34,   37,   36,  660,
       40,   36,   36,   53,   53,   37,   38,   36,   37,   39,
       43,   37,   39,   38,   38,   39,   42,   47,   42,   49,
       55,   47,   55,   42,   47,   56,   49,   58,   73,   58,
       77,   47,   55,  658,   47,   56,   77,   73,  127,   58,
       64,   64,   64,   64,   64,   64,   64,   65,  127,   65,
       65,   65,   65,   65,   65,   65,   70,   70,   70,   70,
       71,   71,   71,   71,   83,   83,   88,   93,   88,   93,
      101,   93,  111,  104,  112,  115,  116,  129,  112,  116,
      101,  121,  129,  141,  101,  104,  141,  181,  121,  111,

      175,  221,  175,  657,  115,  131,  131,  131,  131,  131,
      131,  131,  161,  181,  384,  206,  432,  654,  384,  161,
      206,  221,  451,  451,  461,  653,  432,  461,  479,  479,
      494,  494,  507,  507,  522,  522,  534,  534,  535,  535,
      537,  537,  549,  549,  550,  550,  552,  555,  555,  557,
      557,  558,  558,  562,  562,  569,  569,  570,  570,  574,
      574,  575,  650,  552,  578,  578,  575,  580,  580,  581,
      581,  584,  584,  593,  593,  598,  598,  600,  600,  601,
      601,  602,  602,  606,  606,  649,  562,  615,  615,  620,
      620,  507,  621,  621,  647,  534,  646,  535,  624,  624,

      645,  549,  625,  625,  629,  629,  630,  630,  635,  635,
      637,  637,  638,  638,  569,  644,  570,  648,  648,  656,
      656,  661,  661,  662,  662,  668,  668,  642,  581,  669,
      669,  670,  670,  641,  598,  636,  600,  633,  601,  632,
      602,  628,  606,  671,  671,  627,  615,  623,  620,  672,
      672,  621,  619,  618,  617,  614,  613,  624,  611,  609,
      607,  625,  605,  629,  604,  630,  599,  597,  596,  637,
      595,  638,  594,  592,  591,  590,  589,  588,  656,  587,
      661,  586,  662,  585,  583,  582,  579,  577,  576,  573,
      670,  572,  568,  567,  566,  565,  563,  560,  559,  556,

      554,  551,  671,  548,  547,  546,  545,  544,  672,  675,
      675,  675,  675,  675,  675,  676,  676,  543,  676,  676,
      676,  677,  677,  678,  678,  678,  678,  678,  678,  679,
      679,  679,  679,  679,  679,  680,  680,  541,  680,  680,
      680,  681,  681,  540,  681,  682,  682,  682,  682,  682,
      683,  683,  539,  683,  684,  684,  684,  684,  684,  685,
      685,  538,  685,  686,  686,  532,  686,  687,  687,  531,
      687,  688,  688,  688,  688,  688,  689,  689,  530,  689,
      690,  690,  529,  690,  691,  691,  691,  691,  691,  692,
      692,  692,  692,  692,  693,  693,  693,  693,  693,  694,

      694,  694,  694,  694,  695,  695,  528,  695,  696,  696,
      696,  696,  696,  697,  697,  526,  697,  698,  698,  698,
      698,  698,  525,  524,  521,  520,  519,  518,  517,  516,
      515,  513,  512,  511,  510,  509,  506,  505,  503,  502,
      501,  500,  499,  498,  497,  496,  495,  493,  492,  491,
      490,  489,  488,  487,  486,  485,  484,  483,  482,  481,
      480,  478,  477,  476,  475,  474,  473,  471,  470,  469,
      468,  467,  466,  465,  464,  463,  462,  460,  459,  458,
      457,  456,  455,  454,  453,  452,  450,  449,  448,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  434,  433,

      431,  429,  428,  427,  425,  424,  423,  422,  420,  419,
      418,  417,  416,  415,  414,  413,  412,  410,  409,  408,
      406,  405,  404,  402,  401,  400,  399,  398,  397,  396,
      395,  394,  393,  392,  391,  390,  389,  386,  385,  383,
      382,  380,  379,  378,  377,  376,  375,  374,  373,  372,
      370,  368,  367,  366,  365,  364,  363,  362,  361,  359,
      358,  357,  356,  355,  354,  352,  351,  350,  348,  347,
      345,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  317,  316,  315,  314,  313,

      312,  311,  310,  309,  308,  307,  306,  305,  303,  302,
      301,  300,  299,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  285,  284,  282,  281,  280,  279,  278,
      277,  276,  275,  272,  271,  270,  269,  267,  266,  265,
      264,  262,  261,  260,  259,  257,  256,  255,  254,  253,
      252,  251,  250,  248,  247,  246,  243,  242,  241,  240,
      239,  236,  232,  231,  230,  229,  228,  227,  226,  224,
      223,  222,  220,  219,  218,  217,  216,  215,  212,  211,
      210,  209,  208,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,

      188,  187,  186,  185,  184,  183,  182,  180,  179,  178,
      177,  176,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  162,  160,  159,  158,  157,  156,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  140,  128,  125,  124,  123,  122,  120,
      119,  118,  117,  114,  113,  110,  109,  108,  107,  106,
      105,  103,  102,  100,   98,   97,   96,   95,   94,   92,
       91,   90,   89,   87,   86,   85,   84,   82,   81,   80,
       79,   78,   76,   75,   72,   62,   51,   48,   44,   41,
       28,   27,   25,   24,   23,   17,   11,    7,    3,  674,

      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674,  674,  674,  674,  674,  674,  674,  674,
      674,  674,  674
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner_parser/scanner.ll"
#line 2 "scanner_parser/scanner.ll"
#include "./ast/AST.h"
#include "./parser/ParserLimits.h"
#include "./visitors/DiagnosticCodes.h"
#include "parser.tab.hh"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#define YY_DECL extern "C" int yylex()
extern FILE * flex_output;
extern union _NODE_ yylval;
extern const char *shorthand_source_path;
static std::vector<char *> shorthand_scanner_strings;
static int shorthand_line = 1;
static int shorthand_column = 1;
static std::size_t shorthand_offset = 0;

static char *shorthand_strdup_token(const char *text) {
    char *copy = strdup(text);
    if (copy) shorthand_scanner_strings.push_back(copy);
    return copy;
}

static void shorthand_update_location(const char *text, int length) {
    yylloc.first_line = shorthand_line;
    yylloc.first_column = shorthand_column;
    yylloc.last_line = shorthand_line;
    yylloc.last_column = shorthand_column;
    for (int i = 0; i < length; ++i) {
        yylloc.last_line = shorthand_line;
        yylloc.last_column = shorthand_column;
        ++shorthand_offset;
        if (text[i] == '\n') {
            ++shorthand_line;
            shorthand_column = 1;
        } else {
            ++shorthand_column;
        }
    }
}

static void shorthand_emit_guard_failure() {
    shorthand::parser::emitParserGuardFailure(shorthand_source_path,
                                               yylloc.first_line,
                                               yylloc.first_column,
                                               yylloc.last_line,
                                               yylloc.last_column);
}

static bool shorthand_accept_token_size() {
    if (shorthand::parser::noteTokenBytes(static_cast<std::size_t>(yyleng))) {
        return true;
    }
    shorthand_emit_guard_failure();
    return false;
}

static int shorthand_scanner_failure(const char *code,
                                     const std::string &message) {
    shorthand::parser::recordParserGuardFailure(code, message);
    shorthand_emit_guard_failure();
    return ETOK;
}

#define YY_USER_ACTION                                                        \
    do {                                                                      \
        shorthand_update_location(yytext, yyleng);                            \
        if (!shorthand::parser::noteScannerMatch(                             \
                static_cast<std::size_t>(yyleng))) {                          \
            shorthand_emit_guard_failure();                                  \
            return ETOK;                                                      \
        }                                                                     \
    } while (0);

extern "C" void shorthand_reset_scanner_location() {
    shorthand_line = 1;
    shorthand_column = 1;
    shorthand_offset = 0;
    shorthand::parser::resetParserGuard();
}

extern "C" void shorthand_release_scanner_strings() {
    for (char *value : shorthand_scanner_strings) free(value);
    shorthand_scanner_strings.clear();
}
#line 970 "lex.yy.c"
#line 971 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 94 "scanner_parser/scanner.ll"


#line 1191 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 675 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 900 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 96 "scanner_parser/scanner.ll"
return PACKAGE;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "scanner_parser/scanner.ll"
return MODULE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "scanner_parser/scanner.ll"
return IMPORT;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 99 "scanner_parser/scanner.ll"
return AS;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 100 "scanner_parser/scanner.ll"
return DEF;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 101 "scanner_parser/scanner.ll"
return DOUBLE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 102 "scanner_parser/scanner.ll"
return RETURN;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "scanner_parser/scanner.ll"
return CONTINUE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 104 "scanner_parser/scanner.ll"
return TRUE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 105 "scanner_parser/scanner.ll"
return FALSE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 106 "scanner_parser/scanner.ll"
return MODEL;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 107 "scanner_parser/scanner.ll"
return FORMAT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 108 "scanner_parser/scanner.ll"
return PATH;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 109 "scanner_parser/scanner.ll"
return TASK;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 110 "scanner_parser/scanner.ll"
return PRECISION;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "scanner_parser/scanner.ll"
return INPUT_SHAPE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "scanner_parser/scanner.ll"
return OUTPUT_SHAPE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "scanner_parser/scanner.ll"
return BACKEND_PREFERENCE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "scanner_parser/scanner.ll"
return COMPACT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 115 "scanner_parser/scanner.ll"
return QUALITY_GUARDRAIL;
	YY_BREAK
case 21:
/* rule 21 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 21);
(yy_c_buf_p) = yy_cp = yy_bp + 21;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 116 "scanner_parser/scanner.ll"
return CERTIFICATION_PROFILE;
	YY_BREAK
case 22:
/* rule 22 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 13);
(yy_c_buf_p) = yy_cp = yy_bp + 13;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 117 "scanner_parser/scanner.ll"
return CERTIFICATION;
	YY_BREAK
case 23:
/* rule 23 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 8);
(yy_c_buf_p) = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 118 "scanner_parser/scanner.ll"
return WORKLOAD;
	YY_BREAK
case 24:
/* rule 24 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 16);
(yy_c_buf_p) = yy_cp = yy_bp + 16;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 119 "scanner_parser/scanner.ll"
return MEASUREMENT_PLAN;
	YY_BREAK
case 25:
/* rule 25 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 12);
(yy_c_buf_p) = yy_cp = yy_bp + 12;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 120 "scanner_parser/scanner.ll"
return AI_LIFECYCLE;
	YY_BREAK
case 26:
/* rule 26 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 12);
(yy_c_buf_p) = yy_cp = yy_bp + 12;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 121 "scanner_parser/scanner.ll"
return RAG_PIPELINE;
	YY_BREAK
case 27:
/* rule 27 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 12);
(yy_c_buf_p) = yy_cp = yy_bp + 12;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 122 "scanner_parser/scanner.ll"
return TOKEN_BUDGET;
	YY_BREAK
case 28:
/* rule 28 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 13);
(yy_c_buf_p) = yy_cp = yy_bp + 13;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 123 "scanner_parser/scanner.ll"
return MODEL_ROUTING;
	YY_BREAK
case 29:
/* rule 29 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 10);
(yy_c_buf_p) = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 124 "scanner_parser/scanner.ll"
return GUARDRAILS;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 125 "scanner_parser/scanner.ll"
return GREENAI_CONTRACT_T;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 126 "scanner_parser/scanner.ll"
{
    if (!shorthand_accept_token_size()) return ETOK;
    yylval.string_val = shorthand_strdup_token(yytext);
    return GREENAI_REPORT_BUILTIN;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 131 "scanner_parser/scanner.ll"
{
    if (!shorthand_accept_token_size()) return ETOK;
    yylval.string_val = shorthand_strdup_token(yytext);
    return AI_INFER_BUILTIN;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "scanner_parser/scanner.ll"
return FUNCTIONAL_UNIT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 137 "scanner_parser/scanner.ll"
return SUCCESS_CRITERIA;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 138 "scanner_parser/scanner.ll"
return BOUNDARY;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 139 "scanner_parser/scanner.ll"
return MEASUREMENT_QUALITY;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 140 "scanner_parser/scanner.ll"
return DATA_QUALITY;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 141 "scanner_parser/scanner.ll"
return CARBON_FACTOR;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 142 "scanner_parser/scanner.ll"
return ENERGY_BUDGET_J;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 143 "scanner_parser/scanner.ll"
return CARBON_BUDGET_GCO2E;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 144 "scanner_parser/scanner.ll"
return EVIDENCE_RETENTION;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 145 "scanner_parser/scanner.ll"
return CLAIMS_MODE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 146 "scanner_parser/scanner.ll"
return EVIDENCE_ONLY;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 147 "scanner_parser/scanner.ll"
return GREENAI_MEASURE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 148 "scanner_parser/scanner.ll"
return INFER;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 149 "scanner_parser/scanner.ll"
return TENSOR;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 150 "scanner_parser/scanner.ll"
return INT8;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 151 "scanner_parser/scanner.ll"
return FP16;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 152 "scanner_parser/scanner.ll"
return FP32;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 153 "scanner_parser/scanner.ll"
return BF16;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 154 "scanner_parser/scanner.ll"
return INT4;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 155 "scanner_parser/scanner.ll"
return FP64;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 156 "scanner_parser/scanner.ll"
return ONNX;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 157 "scanner_parser/scanner.ll"
return ENGINE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 158 "scanner_parser/scanner.ll"
return TORCHSCRIPT;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 159 "scanner_parser/scanner.ll"
return OPENVINO_IR;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 160 "scanner_parser/scanner.ll"
return GGUF;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 161 "scanner_parser/scanner.ll"
return TENSORRT;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 162 "scanner_parser/scanner.ll"
return ONNXRUNTIME_TENSORRT;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 163 "scanner_parser/scanner.ll"
return ONNXRUNTIME_CUDA;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 164 "scanner_parser/scanner.ll"
return ONNXRUNTIME_CPU;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 165 "scanner_parser/scanner.ll"
return OPENVINO;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 166 "scanner_parser/scanner.ll"
return LIBTORCH;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 167 "scanner_parser/scanner.ll"
return LLAMACPP;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 168 "scanner_parser/scanner.ll"
return FALLBACK;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 169 "scanner_parser/scanner.ll"
return MQ1;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 170 "scanner_parser/scanner.ll"
return MQ2;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 171 "scanner_parser/scanner.ll"
return MQ3;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 172 "scanner_parser/scanner.ll"
return MQ4;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 173 "scanner_parser/scanner.ll"
return DQ1;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 174 "scanner_parser/scanner.ll"
return DQ2;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 175 "scanner_parser/scanner.ll"
return DQ3;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 176 "scanner_parser/scanner.ll"
return DQ4;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 177 "scanner_parser/scanner.ll"
return LOCATION;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 178 "scanner_parser/scanner.ll"
return CI_CD;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 179 "scanner_parser/scanner.ll"
return THIRDPARTY;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 180 "scanner_parser/scanner.ll"
return ACCELERATOR;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 181 "scanner_parser/scanner.ll"
return COMPUTE;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 182 "scanner_parser/scanner.ll"
return STORAGE;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 183 "scanner_parser/scanner.ll"
return NETWORK;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 184 "scanner_parser/scanner.ll"
return INT;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 185 "scanner_parser/scanner.ll"
return FLOAT;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 186 "scanner_parser/scanner.ll"
return STRING;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 187 "scanner_parser/scanner.ll"
return BOOL;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 188 "scanner_parser/scanner.ll"
return VOID;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 189 "scanner_parser/scanner.ll"
return LOOP;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 190 "scanner_parser/scanner.ll"
return WHILE;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 191 "scanner_parser/scanner.ll"
return IF;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 192 "scanner_parser/scanner.ll"
return ELSE;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 193 "scanner_parser/scanner.ll"
return GOTO;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 194 "scanner_parser/scanner.ll"
return PRINT;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 195 "scanner_parser/scanner.ll"
return READ;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 196 "scanner_parser/scanner.ll"
return BREAK;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 197 "scanner_parser/scanner.ll"
return '+';
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 198 "scanner_parser/scanner.ll"
return '-';
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 199 "scanner_parser/scanner.ll"
return '*';
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 200 "scanner_parser/scanner.ll"
;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 201 "scanner_parser/scanner.ll"
;
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 202 "scanner_parser/scanner.ll"
;
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 203 "scanner_parser/scanner.ll"
{
    return shorthand_scanner_failure(
        shorthand::diagnostics::ScannerUnterminatedComment,
        "unterminated block comment");
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 208 "scanner_parser/scanner.ll"
return '/';
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 209 "scanner_parser/scanner.ll"
return '%';
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 210 "scanner_parser/scanner.ll"
return ';';
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 211 "scanner_parser/scanner.ll"
return ',';
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 212 "scanner_parser/scanner.ll"
return ':';
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 213 "scanner_parser/scanner.ll"
return '.';
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 214 "scanner_parser/scanner.ll"
{
    if (!shorthand::parser::enterDelimiter()) {
        shorthand_emit_guard_failure();
        return ETOK;
    }
    return '{';
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 221 "scanner_parser/scanner.ll"
{ shorthand::parser::leaveDelimiter(); return '}'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 222 "scanner_parser/scanner.ll"
return '=';
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 223 "scanner_parser/scanner.ll"
{
    if (!shorthand::parser::enterDelimiter()) {
        shorthand_emit_guard_failure();
        return ETOK;
    }
    return '[';
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 230 "scanner_parser/scanner.ll"
{ shorthand::parser::leaveDelimiter(); return ']'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 231 "scanner_parser/scanner.ll"
{ return ARROW; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 232 "scanner_parser/scanner.ll"
{
    if (!shorthand::parser::enterDelimiter()) {
        shorthand_emit_guard_failure();
        return ETOK;
    }
    return '(';
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 239 "scanner_parser/scanner.ll"
{ shorthand::parser::leaveDelimiter(); return ')'; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 240 "scanner_parser/scanner.ll"
return LESS;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 241 "scanner_parser/scanner.ll"
return GREATER;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 242 "scanner_parser/scanner.ll"
return LESS_OR_EQUAL;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 243 "scanner_parser/scanner.ll"
return GREATER_OR_EQUAL;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 244 "scanner_parser/scanner.ll"
return EQUAL;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 245 "scanner_parser/scanner.ll"
return NOT_EQUAL;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 246 "scanner_parser/scanner.ll"
return OR;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 247 "scanner_parser/scanner.ll"
return AND;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 249 "scanner_parser/scanner.ll"
{
    if (!shorthand_accept_token_size()) return ETOK;
    yylval.float_val = atof(yytext);
    return FLOAT_LITERAL;
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 254 "scanner_parser/scanner.ll"
{
    if (!shorthand_accept_token_size()) return ETOK;
    yylval.int_val = atoi(yytext);
    fprintf(flex_output, "integer literal: %s\n", yytext);
    return INT_LITERAL;
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 260 "scanner_parser/scanner.ll"
{
    if (!shorthand_accept_token_size()) return ETOK;
    yylval.string_val = shorthand_strdup_token(yytext);
    fprintf(flex_output, "identifier: %s\n", yytext);
    return IDENTIFIER;
}
	YY_BREAK
case 126:
/* rule 126 can match eol */
YY_RULE_SETUP
#line 266 "scanner_parser/scanner.ll"
{
    if (!shorthand_accept_token_size()) return ETOK;
    yylval.string_val = shorthand_strdup_token(yytext);
    fprintf(flex_output, "string literal: %s\n", yytext);
    return STRING_LITERAL;
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 272 "scanner_parser/scanner.ll"
{
    if (!shorthand_accept_token_size()) return ETOK;
    return shorthand_scanner_failure(
        shorthand::diagnostics::ScannerUnterminatedString,
        "unterminated string literal");
}
	YY_BREAK
case 128:
/* rule 128 can match eol */
YY_RULE_SETUP
#line 278 "scanner_parser/scanner.ll"
{ }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 279 "scanner_parser/scanner.ll"
{
    const unsigned int value = static_cast<unsigned char>(yytext[0]);
    char message[64];
    std::snprintf(message, sizeof(message), "unexpected byte 0x%02X", value);
    fprintf(flex_output, "Unexpected token encountered: %s\n", yytext);
    return shorthand_scanner_failure(
        shorthand::diagnostics::ScannerUnexpectedCharacter,
        message);
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 289 "scanner_parser/scanner.ll"
ECHO;
	YY_BREAK
#line 2009 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 675 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 675 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 674);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 289 "scanner_parser/scanner.ll"
