#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${ROOT_DIR}/Compiler_new_ws/Short_Hand/src"
BUILD_DIR="${ROOT_DIR}/Compiler_new_ws/Short_Hand/build"
INSTALL_HINT="sudo apt-get install -y build-essential make g++ flex bison libfl-dev llvm llvm-dev clang clang-format cmake ninja-build"

UNAME_S="$(uname -s)"
UNAME_M="$(uname -m)"
echo "ShortHand setup for ${UNAME_S}/${UNAME_M}"
case "${UNAME_S}/${UNAME_M}" in
  Linux/x86_64|Linux/aarch64|Darwin/x86_64|Darwin/arm64) ;;
  *) echo "warning: untested platform ${UNAME_S}/${UNAME_M}" ;;
esac

missing=0
for tool in make g++ bison flex llvm-config llc clang; do
  if ! command -v "${tool}" >/dev/null 2>&1; then
    echo "error: required tool missing: ${tool}" >&2
    missing=1
  fi
done
if [[ "${missing}" -ne 0 ]]; then
  echo "Ubuntu install hint: ${INSTALL_HINT}" >&2
  exit 1
fi

echo "Tool versions:"
g++ --version | head -n 1
bison --version | head -n 1
flex --version
llvm-config --version
llc --version | head -n 1
clang --version | head -n 1

echo "Checking Flex runtime linkage..."
if ! printf 'int main(){return 0;}\n' | g++ -x c++ - -lfl -o /tmp/shorthand_check_flex_lib >/tmp/shorthand_check_flex_lib.out 2>/tmp/shorthand_check_flex_lib.err; then
  echo "error: Flex runtime library is not linkable. On Ubuntu install libfl-dev." >&2
  cat /tmp/shorthand_check_flex_lib.err >&2
  exit 1
fi
rm -f /tmp/shorthand_check_flex_lib /tmp/shorthand_check_flex_lib.out /tmp/shorthand_check_flex_lib.err

cat > "${ROOT_DIR}/shorthand_env.sh" <<ENV
# Generated by setup_build_infra.sh
export SHORTHAND_ROOT="${ROOT_DIR}"
export SHORTHAND_SRC="${SRC_DIR}"
export LLVM_CONFIG="$(command -v llvm-config)"
export PATH="${BUILD_DIR}:\$PATH"
ENV

make -C "${SRC_DIR}" compiler green_ai_tool

if [[ -n "${ONNXRUNTIME_ROOT:-}" ]]; then
  echo "ONNX Runtime enabled from ${ONNXRUNTIME_ROOT}; building optional ai_app."
  make -C "${SRC_DIR}" ai_app
else
  echo "Optional ai_app build skipped: ONNXRUNTIME_ROOT is not set."
fi

if [[ -n "${LIBTORCH_ROOT:-}" ]]; then
  echo "LibTorch enabled from ${LIBTORCH_ROOT}; building optional ai_train."
  make -C "${SRC_DIR}" ai_train
else
  echo "Optional ai_train build skipped: LIBTORCH_ROOT is not set."
fi

bash "${ROOT_DIR}/scripts/validate_language.sh" --strict
bash "${ROOT_DIR}/scripts/smoke_test.sh"

echo "Setup completed. Run: source ./shorthand_env.sh"
