#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${ROOT_DIR}/Compiler_new_ws/Short_Hand/src"
UNAME_S="$(uname -s)"; UNAME_M="$(uname -m)"
echo "ShortHand setup for ${UNAME_S}/${UNAME_M}"
case "${UNAME_S}/${UNAME_M}" in
  Linux/x86_64|Linux/aarch64|Darwin/x86_64|Darwin/arm64) ;;
  *) echo "warning: untested platform ${UNAME_S}/${UNAME_M}" ;;
esac
missing=0
for tool in make g++ bison; do command -v "$tool" >/dev/null 2>&1 || { echo "error: required tool missing: $tool" >&2; missing=1; }; done
command -v flex >/dev/null 2>&1 || { echo "error: required tool missing: flex" >&2; missing=1; }
command -v llvm-config >/dev/null 2>&1 || { echo "error: required tool missing: llvm-config" >&2; missing=1; }
[[ "$missing" -eq 0 ]] || exit 1
cat > "${ROOT_DIR}/shorthand_env.sh" <<ENV
# Generated by setup_build_infra.sh
export SHORTHAND_ROOT="${ROOT_DIR}"
export SHORTHAND_SRC="${SRC_DIR}"
export PATH="${ROOT_DIR}/Compiler_new_ws/Short_Hand/build:\$PATH"
ENV
if [[ -n "${ONNXRUNTIME_ROOT:-}" ]]; then echo "ONNX Runtime enabled from ${ONNXRUNTIME_ROOT}"; else echo "ONNX Runtime not enabled: set ONNXRUNTIME_ROOT to build optional runtime support."; fi
if [[ -n "${LIBTORCH_ROOT:-}" ]]; then echo "LibTorch enabled from ${LIBTORCH_ROOT}"; else echo "LibTorch not enabled: set LIBTORCH_ROOT to build optional training demo."; fi
make -C "${SRC_DIR}" compiler green_ai_tool
if [[ -n "${ONNXRUNTIME_ROOT:-}" ]]; then make -C "${SRC_DIR}" ai_app; else echo "AI app optional build skipped (ONNXRUNTIME_ROOT unset)."; fi
if [[ -n "${LIBTORCH_ROOT:-}" ]]; then make -C "${SRC_DIR}" ai_train; else echo "AI train optional build skipped (LIBTORCH_ROOT unset)."; fi
bash "${ROOT_DIR}/scripts/validate_language.sh" --strict
bash "${ROOT_DIR}/scripts/smoke_test.sh"
echo "Setup completed. Run: source ./shorthand_env.sh"
