#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${ROOT_DIR}/Compiler_new_ws/Short_Hand/src"
UNAME_S="$(uname -s)"
UNAME_M="$(uname -m)"

printf 'ShortHand setup for %s/%s\n' "${UNAME_S}" "${UNAME_M}"
case "${UNAME_S}/${UNAME_M}" in
  Linux/x86_64|Linux/aarch64|Darwin/x86_64|Darwin/arm64) ;;
  *) printf 'warning: untested platform %s/%s\n' "${UNAME_S}" "${UNAME_M}" ;;
esac

missing=0
required_tools=(make g++ bison flex llvm-config llc clang)
for tool in "${required_tools[@]}"; do
  if ! command -v "${tool}" >/dev/null 2>&1; then
    printf 'error: required tool missing: %s\n' "${tool}" >&2
    missing=1
  fi
done
if [[ "${missing}" -ne 0 ]]; then
  cat >&2 <<'MSG'
Install the mandatory ShortHand toolchain before running setup:
  Ubuntu: sudo apt-get install build-essential make g++ flex bison libfl-dev llvm llvm-dev clang clang-format cmake ninja-build
MSG
  exit 1
fi

printf 'Checking Flex runtime linkability...\n'
if ! printf 'int main(){return 0;}\n' | g++ -x c++ - -lfl -o /tmp/shorthand_check_flex_lib >/tmp/shorthand_check_flex_lib.out 2>/tmp/shorthand_check_flex_lib.err; then
  cat /tmp/shorthand_check_flex_lib.err >&2 || true
  rm -f /tmp/shorthand_check_flex_lib /tmp/shorthand_check_flex_lib.out /tmp/shorthand_check_flex_lib.err
  printf 'error: Flex runtime library is not linkable. Install libfl-dev (Ubuntu) or equivalent.\n' >&2
  exit 1
fi
rm -f /tmp/shorthand_check_flex_lib /tmp/shorthand_check_flex_lib.out /tmp/shorthand_check_flex_lib.err

printf 'Toolchain versions:\n'
printf '  g++: '; g++ --version | head -n 1
printf '  bison: '; bison --version | head -n 1
printf '  flex: '; flex --version | head -n 1
printf '  llvm-config: '; llvm-config --version
printf '  llc: '; llc --version | head -n 1
printf '  clang: '; clang --version | head -n 1

cat > "${ROOT_DIR}/shorthand_env.sh" <<ENV
# Generated by setup_build_infra.sh
export SHORTHAND_ROOT="${ROOT_DIR}"
export SHORTHAND_SRC="${SRC_DIR}"
export PATH="${ROOT_DIR}/Compiler_new_ws/Short_Hand/build:\$PATH"
ENV
printf 'Wrote %s\n' "${ROOT_DIR}/shorthand_env.sh"

if [[ -n "${ONNXRUNTIME_ROOT:-}" ]]; then
  printf 'ONNX Runtime enabled from %s\n' "${ONNXRUNTIME_ROOT}"
else
  printf 'Optional AI app build skipped: ONNXRUNTIME_ROOT is not set.\n'
fi
if [[ -n "${LIBTORCH_ROOT:-}" ]]; then
  printf 'LibTorch enabled from %s\n' "${LIBTORCH_ROOT}"
else
  printf 'Optional AI training build skipped: LIBTORCH_ROOT is not set.\n'
fi

make -C "${SRC_DIR}" compiler green_ai_tool
if [[ -n "${ONNXRUNTIME_ROOT:-}" ]]; then
  make -C "${SRC_DIR}" ai_app
fi
if [[ -n "${LIBTORCH_ROOT:-}" ]]; then
  make -C "${SRC_DIR}" ai_train
fi

bash "${ROOT_DIR}/scripts/validate_language.sh" --strict
bash "${ROOT_DIR}/scripts/smoke_test.sh"
printf 'Setup completed. Run: source ./shorthand_env.sh\n'
