apiVersion: v1
kind: Pod
metadata:
  name: shorthand-demo
spec:
  containers:
    - name: shorthand
      image: shorthand:beta
      command: ["short_hand"]
      args: ["Compiler_new_ws/Short_Hand/examples/greenai_report.short", "run"]
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
