#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
WORK_DIR="$(mktemp -d /tmp/shorthand-pr99-contract.XXXXXX)"
trap 'rm -rf "${WORK_DIR}"' EXIT

REPORT="${WORK_DIR}/report.json"
SHORTHAND_PRODUCTION_RC_REPORT="${REPORT}" bash "${ROOT_DIR}/scripts/check_production_rc.sh" --contract
jq -e '
  .schema == "shorthand.enterprise.pilot_rc.v1" and
  .execution_mode == "contract" and
  .production_scope == "linux-x64-cpu-v1" and
  .production_claim == false and
  .accelerator_production_support == false and
  .mandatory_skips == 0 and
  .release_candidate_decision == "blocked_by_retained_evidence" and
  (.compiler_blockers | map(.id) | sort) == ["TST017","TST025","TST026"] and
  (.lifecycle.clean_install == false) and
  (.deployment.contract_checked == false)
' "${REPORT}" >/dev/null

cp "${ROOT_DIR}/docs/production_rc_scope.tsv" "${WORK_DIR}/scope.tsv"
sed -i 's/^production_scope\tlinux-x64-cpu-v1$/production_scope\tlinux-x64-gpu-v1/' "${WORK_DIR}/scope.tsv"
if SHORTHAND_PRODUCTION_RC_SCOPE_FILE="${WORK_DIR}/scope.tsv" \
  SHORTHAND_PRODUCTION_RC_REPORT="${WORK_DIR}/bad-scope.json" \
  bash "${ROOT_DIR}/scripts/check_production_rc.sh" --contract >/dev/null 2>&1; then
  echo "error: invalid accelerator scope unexpectedly passed" >&2
  exit 1
fi

cp "${ROOT_DIR}/docs/production_rc_scope.tsv" "${WORK_DIR}/claim.tsv"
sed -i 's/^production_claim\tfalse$/production_claim\ttrue/' "${WORK_DIR}/claim.tsv"
if SHORTHAND_PRODUCTION_RC_SCOPE_FILE="${WORK_DIR}/claim.tsv" \
  SHORTHAND_PRODUCTION_RC_REPORT="${WORK_DIR}/bad-claim.json" \
  bash "${ROOT_DIR}/scripts/check_production_rc.sh" --contract >/dev/null 2>&1; then
  echo "error: unsupported production claim unexpectedly passed" >&2
  exit 1
fi

cp "${ROOT_DIR}/tests/coverage/compiler_test_coverage_matrix.tsv" "${WORK_DIR}/matrix.tsv"
sed -i 's/^TST027\tproduction release-candidate gate\timplemented/TST027\tproduction release-candidate gate\topen/' "${WORK_DIR}/matrix.tsv"
if SHORTHAND_PRODUCTION_RC_MATRIX_FILE="${WORK_DIR}/matrix.tsv" \
  SHORTHAND_PRODUCTION_RC_REPORT="${WORK_DIR}/bad-matrix.json" \
  bash "${ROOT_DIR}/scripts/check_production_rc.sh" --contract >/dev/null 2>&1; then
  echo "error: open TST027 unexpectedly passed" >&2
  exit 1
fi

# A clean configure/build has install rules but no install_manifest.txt yet.
# Stop at the lifecycle child with a distinctive failure: this exercises the
# real RC dispatcher without pretending to execute an installed SDK locally.
# Hosted CI separately runs the complete real lifecycle against the built SDK.
mkdir -p "${WORK_DIR}/fresh-build"
printf '%s\n' '# Configured install rules; manifest is generated by installation.' \
  >"${WORK_DIR}/fresh-build/cmake_install.cmake"
ln -s "$(type -P false)" "${WORK_DIR}/fresh-build/short_hand"
cat >"${WORK_DIR}/lifecycle-entry.bash" <<'BASH'
if [[ "${0##*/}" == "check_installed_sdk_lifecycle.sh" ]]; then
  [[ ! -e "$1/install_manifest.txt" ]] || exit 96
  printf '%s\n' 'fresh lifecycle entered' >"${PR99_LIFECYCLE_MARKER}"
  exit "${PR99_LIFECYCLE_STATUS:-97}"
fi
BASH
if BASH_ENV="${WORK_DIR}/lifecycle-entry.bash" \
  PR99_LIFECYCLE_MARKER="${WORK_DIR}/lifecycle-entered" \
  SHORTHAND_PRODUCTION_RC_REPORT="${WORK_DIR}/fresh-report.json" \
  bash "${ROOT_DIR}/scripts/check_production_rc.sh" \
    "${WORK_DIR}/fresh-build" "${WORK_DIR}/fresh-prefix" >"${WORK_DIR}/fresh.out" 2>&1; then
  echo "error: failed SDK lifecycle unexpectedly produced RC success" >&2
  exit 1
else
  lifecycle_status=$?
fi
if [[ "${lifecycle_status}" != 97 || ! -s "${WORK_DIR}/lifecycle-entered" ]]; then
  cat "${WORK_DIR}/fresh.out" >&2
  echo "error: clean-build RC gate did not reach the lifecycle installer (status=${lifecycle_status})" >&2
  exit 1
fi
[[ ! -e "${WORK_DIR}/fresh-report.json" ]] || {
  echo "error: failed SDK lifecycle emitted an RC report" >&2
  exit 1
}

# A child reporting success without generating a manifest must still fail.
if BASH_ENV="${WORK_DIR}/lifecycle-entry.bash" \
  PR99_LIFECYCLE_MARKER="${WORK_DIR}/manifest-check-entered" \
  PR99_LIFECYCLE_STATUS=0 \
  SHORTHAND_PRODUCTION_RC_REPORT="${WORK_DIR}/missing-manifest-report.json" \
  bash "${ROOT_DIR}/scripts/check_production_rc.sh" \
    "${WORK_DIR}/fresh-build" "${WORK_DIR}/fresh-prefix" >"${WORK_DIR}/missing-manifest.out" 2>&1; then
  echo "error: lifecycle without generated manifest unexpectedly passed" >&2
  exit 1
fi
[[ -s "${WORK_DIR}/manifest-check-entered" ]]
grep -Fq 'CMake install manifest is missing after lifecycle:' "${WORK_DIR}/missing-manifest.out"
[[ ! -e "${WORK_DIR}/missing-manifest-report.json" ]]

# A directory with a compiler but no generated install rules is not configured.
mkdir -p "${WORK_DIR}/unconfigured-build"
ln -s "$(type -P false)" "${WORK_DIR}/unconfigured-build/short_hand"
if SHORTHAND_PRODUCTION_RC_REPORT="${WORK_DIR}/unconfigured-report.json" \
  bash "${ROOT_DIR}/scripts/check_production_rc.sh" \
    "${WORK_DIR}/unconfigured-build" "${WORK_DIR}/unconfigured-prefix" >"${WORK_DIR}/unconfigured.out" 2>&1; then
  echo "error: unconfigured build unexpectedly passed" >&2
  exit 1
fi
grep -Fq 'CMake install rules are missing:' "${WORK_DIR}/unconfigured.out"
[[ ! -e "${WORK_DIR}/unconfigured-report.json" ]]

echo "PASS PR99 production RC contract and negative lifecycle/scope cases"
